# Generated by Django 4.1.6 on 2023-03-30 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tonsToTroy', models.FloatField()),
                ('gramsToTroy', models.FloatField()),
                ('troyToTroy', models.FloatField()),
                ('kiloToTroy', models.FloatField()),
                ('poundToTroy', models.FloatField()),
                ('ounceToTroy', models.FloatField()),
            ],
        ),
    ]
